language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"

before_install:
    - sudo apt-get -qq update
    - pip install --upgrade pip setuptools

install: 
    - pip install -r requirements.txt
    - git clone -b new-types git@github.com:phanrahan/magmacore.git
    - pip install -e magmacore
    - git clone git@github.com:phanrahan/loam.git
    - pip install -e loam
    - pip install pytest-cov
    - pip install -e .

script: 
    - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then py.test --cov=mantle tests;else pytest --cov=mantle tests; fi
